"""Frozen-embedding feature, classifier, and persistence contracts."""

from biominer.ml.training_features import (
    CATEGORICAL_MODEL_FEATURE_COLUMNS,
    FEW_SHOT_TRAINING_FEATURES_FILE,
    FEW_SHOT_TRAINING_FEATURES_SCHEMA_VERSION,
    LABEL_COLUMNS,
    MODEL_FEATURE_COLUMNS,
    NUMERIC_MODEL_FEATURE_COLUMNS,
    PROHIBITED_SOURCE_FEATURE_FIELDS,
    DetectionQualityFeatures,
    FewShotTrainingExample,
    FrozenEmbeddingFeatures,
    GeographicEvidenceFeatures,
    ReferenceEvidenceFeatures,
    TextEvidenceFeatures,
    TrainingLabel,
    TrainingProvenance,
    build_few_shot_training_features,
    feature_schema_fingerprint,
    few_shot_training_features_schema,
    load_few_shot_training_features,
    validate_few_shot_training_features,
    write_few_shot_training_features,
)

__all__ = [
    "CATEGORICAL_MODEL_FEATURE_COLUMNS",
    "FEW_SHOT_TRAINING_FEATURES_FILE",
    "FEW_SHOT_TRAINING_FEATURES_SCHEMA_VERSION",
    "LABEL_COLUMNS",
    "MODEL_FEATURE_COLUMNS",
    "NUMERIC_MODEL_FEATURE_COLUMNS",
    "PROHIBITED_SOURCE_FEATURE_FIELDS",
    "DetectionQualityFeatures",
    "FewShotTrainingExample",
    "FrozenEmbeddingFeatures",
    "GeographicEvidenceFeatures",
    "ReferenceEvidenceFeatures",
    "TextEvidenceFeatures",
    "TrainingLabel",
    "TrainingProvenance",
    "build_few_shot_training_features",
    "feature_schema_fingerprint",
    "few_shot_training_features_schema",
    "load_few_shot_training_features",
    "validate_few_shot_training_features",
    "write_few_shot_training_features",
]
